<div class="container">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $this->getPageTitle(); ?></h2>
    </div>
    <div class="row">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center">Micro Framework do Zero</h1>
            <p class="text-center">
                Este é um micro framework MVC em PHP, construído como teste para WebJump !
            </p>
        </div>
    </div>
</div>