<div class="container">
    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>

        <form action="/category/<?php echo $this->view->category->id ?>/update" method="post" accept-charset="utf-8">

            <div class="col-sm-10">
                <div class="form-group <?php echo ($this->errors['name']) ? 'has-error' : '' ?>">
                    <label for="name" class="control-label">Nome</label>
                    <input required="true" type="text" name="name" class="form-control" value="<?php echo (isset($this->inputs['name'])) ? $this->inputs['name'] : $this->view->category->name ?>">
                    <?php if ($this->errors['name']): ?>
                        <span class="help-block"><?php echo $this->errors['name'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="form-group <?php echo ($this->errors['code']) ? 'has-error' : '' ?>">
                    <label for="code" class="control-label">Código</label>
                    <input required="true" type="text" name="code" class="form-control" value="<?php echo (isset($this->inputs['code'])) ? $this->inputs['code'] : $this->view->category->code ?>">
                    <?php if ($this->errors['code']): ?>
                        <span class="help-block"><?php echo $this->errors['code'] ?></span>
                    <?php endif; ?>
                </div>

            </div>

            <div class="col-xs-12">
                <a href="/categorys" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
</div>