<div class="container">
    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>

        <form action="/product/store" method="post" accept-charset="utf-8">

            <div class="col-sm-10">
                <div class="form-group <?php echo ($this->errors['name']) ? 'has-error' : '' ?>">
                    <label for="name" class="control-label">Nome</label>
                    <input required="true" type="text" name="name" class="form-control"
                           value="<?php echo (isset($this->inputs['name'])) ? $this->inputs['name'] : '' ?>">
                    <?php if ($this->errors['name']): ?>
                        <span class="help-block"><?php echo $this->errors['name'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="form-group <?php echo ($this->errors['code']) ? 'has-error' : '' ?>">
                    <label for="code" class="control-label">Código</label>
                    <input required="true" type="text" name="code" class="form-control"
                           value="<?php echo (isset($this->inputs['code'])) ? $this->inputs['code'] : '' ?>">
                    <?php if ($this->errors['code']): ?>
                        <span class="help-block"><?php echo $this->errors['code'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="form-group <?php echo ($this->errors['price']) ? 'has-error' : '' ?>">
                    <label for="price" class="control-label">Preço</label>
                    <input required="true" type="number" step=".01" min="0" pattern="^\d*(\.\d{0,2})?$" name="price" class="form-control"
                           value="<?php echo (isset($this->inputs['price'])) ? $this->inputs['price'] : '' ?>">
                    <?php if ($this->errors['price']): ?>
                        <span class="help-block"><?php echo $this->errors['price'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="form-group <?php echo ($this->errors['qtd']) ? 'has-error' : '' ?>">
                    <label for="qtd" class="control-label">Quantidade</label>
                    <input required="true" type="number" min="0" name="qtd" class="form-control"
                           value="<?php echo (isset($this->inputs['qtd'])) ? $this->inputs['qtd'] : '' ?>">
                    <?php if ($this->errors['qtd']): ?>
                        <span class="help-block"><?php echo $this->errors['qtd'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="form-group <?php echo ($this->errors['description']) ? 'has-error' : '' ?>">
                    <label for="description" class="control-label">Descrição</label>
                    <textarea name="description" class="form-control"
                              rows="10"><?php echo (isset($this->inputs['description'])) ? $this->inputs['description'] : '' ?></textarea>
                    <?php if ($this->errors['description']): ?>
                        <span class="help-block"><?php echo $this->errors['description'] ?></span>
                    <?php endif; ?>
                </div>
            </div>

            <div class="col-sm-2">
                <div class="form-group <?php echo ($this->errors['category_id']) ? 'has-error' : '' ?>">
                    <label for="title" class="control-label">Categorias</label>
                    <?php foreach ($this->view->categories as $cat) : ?>
                        <div class="checkbox">
                            <label>
                                <input required="true" type="checkbox" name="category_id[]"
                                       value="<?php echo $cat->id ?>"> <?php echo $cat->name ?>
                            </label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="col-xs-12">
                <a href="/products" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
</div>